#!/usr/bin/env python

# Initialization - DO NOT REMOVE
from helpers.initialize import *
##############################################################
### Customizations start here ################################
##############################################################

fail_if_not_root()  # Comment out if 'root' is not required.

### Install packages
package_update()
package('git-core')
package('vim screen htop curl wget traceroute')
package('build-essential')
package('libjpeg-progs')
package('libsqlite3-dev')
package('libmagickwand-dev imagemagick')

### Users
add_user('deploy')

### Run recipes
recipe('setup_keys', 'deploy')
recipe('customize_bash','deploy')
recipe('add_sudoer', 'deploy')
recipe('secure_ssh')
recipe('rbenv')
recipe('ruby', '1.9.3-p125', 'deploy')
recipe('nginx')
recipe('memcached', '1.4.13')
recipe('mariadb')

### Show the Finished banner
finished()

