#!/usr/bin/env python

if not is_installed('mariadb'):
  run("apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db")
  copy('mariadb.list', '/etc/apt/sources.list.d/')
  package_update()
  package('mariadb-server')
  package('libmariadbclient-dev')
  set_installed('mariadb')
