#!/usr/bin/env python

if not is_installed('nginx'):
  copy('nginx_signing.key', '/tmp/')
  cd('/tmp')
  run('apt-key add nginx_signing.key')

  copy('nginx.list', '/etc/apt/sources.list.d/')
  package_update()
  package('nginx')
  copy('nginx.conf', '/etc/nginx/nginx.conf')
  set_installed('nginx')
