#!/usr/bin/env python

if not is_installed('rbenv'):
  package('libreadline-dev')

  run('chown -R deploy:deploy /home/deploy/')
  run_as('deploy', 'git clone git://github.com/sstephenson/rbenv.git /home/deploy/.rbenv')
  copy('rbenv.profile', '/home/deploy/.rbenv.profile')
  run('chown deploy:deploy /home/deploy/.rbenv.profile')
  add_line("source  ~/.rbenv.profile", '/home/deploy/.bashrc')
  run_as('deploy', 'mkdir -p /home/deploy/.rbenv/plugins')
  run_as('deploy', 'git clone git://github.com/sstephenson/ruby-build.git /home/deploy/.rbenv/plugins/ruby-build')

  set_installed('rbenv')
